version: "3.8"

services:
  next:
    container_name: Next
    build:
      context: ./Next
      dockerfile: ./Dockerfile.development
      args:
        BACKEND_URI: ${BACKEND_URI}
    volumes:
      - '/next/node_modules'
      - './Next:/next'
    stdin_open: true
    ports:
      - 3001:3001
  frontend:
    container_name: Frontend
    build: 
      context: ./Frontend
      dockerfile: ./Dockerfile.development
      args: 
        BACKEND_URI: ${BACKEND_URI}
    volumes:
      # Note must include node_modules as a seperate volume
      - '/app/node_modules'
      - './Frontend:/app'
    stdin_open: true
    ports:
      - 3000:3000
  backend:
    container_name: go_backend
    build: 
      context: ./Backend
      dockerfile: ./Dockerfile.development
    depends_on:
      - db
    volumes:
      - './Backend:/go/src/cms.csesoc.unsw.edu.au'
      - './Backend/go.mod:/go/src/cms.csesoc.unsw.edu.au/go.mod'
      - 'document_data:/var/lib/documents/data'
    ports:
      - 8080:8080
    environment:
      - FRONTEND_URI=${FRONTEND_URI}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_PORT=${PG_PORT}
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - './Postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
      - 'pg_data:/var/lib/postgresql/data'
  staging_db:
    container_name: pg_container_testing
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: cms_testing_db
    ports:
      - 1234:5432
    volumes:
      - './Postgres/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql'
      - 'staging_data:/var/lib/postgresql/data'
volumes:
  pg_data:
  staging_data:
  document_data:
