services:
  events-service:
    container_name: events-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - FB_TOKEN=please_replace_me
