# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, prototype, "renovate/*"]
  pull_request:
    branches: [main, prototype]

env:
  PG_PORT: 5432

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  frontend_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: type check
        run: cd Frontend && npm install && npm run types
      - name: react tests
        run: cd Frontend && npm test
